# Generated by Django 4.2.5 on 2023-09-19 10:09

from django.db import migrations, models
import ssl_checker_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_checker_app', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=ssl_checker_app.models.default_profile_picture, null=True, upload_to='profile_pics/'),
        ),
    ]
