# Generated by Django 4.2.4 on 2023-09-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_checker_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sslcertificate',
            name='issuer',
        ),
    ]
