# Generated by Django 4.2.4 on 2023-09-14 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_checker_app', '0003_alter_sslcertificate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslcertificate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
